### ISSUE TITLE
导出sql文件

### ISSUE THREAD

**Issue by am-abudu** [jiangmitiao/hexo-2-typecho#1]
作者你好，是否能做一个直接导出sql文件的功能呢，我的数据库一直连接不上navicat

**Comment by zhghg** [comment]
> 作者你好，是否能做一个直接导出sql文件的功能呢，我的数据库一直连接不上navicat

可以的，之前没这么做的原因是文章内单引号双引号会引起sql导入异常，这块我再看看怎么解掉。
